version: '3'
services:
  app:
    build: .
    entrypoint: sh -c "yarn install && npm rebuild && yarn run start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - redis

  redis:
    image: redis:6.2.6-alpine3.14
